//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDuLich.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebDuLichEntities : DbContext
    {
        public WebDuLichEntities()
            : base("name=WebDuLichEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_slide_dulich> tbl_slide_dulich { get; set; }
        public virtual DbSet<tbl_menu_dulich> tbl_menu_dulich { get; set; }
        public virtual DbSet<tbl_new_dulich> tbl_new_dulich { get; set; }
    }
}
